// Fair, same-runtime comparison: eff-sharp's Fable-generated JS vs stock Effect,
// both on this Node, both driven through their async/Promise runner with the same
// tinybench harness. This is the comparison the old RESULTS.md could not make —
// that one timed eff-sharp on .NET (RyuJIT) against stock on JS, so its ratios
// carried a "fairness" caveat. Here both sides are JS on the same V8.
//
// Prereqs:
//   1. npm install            (effect + tinybench)
//   2. dotnet fable port/Port.Bench.fsproj --lang javascript -o port/out --noCache
// Run:  node compare.mjs
//
// Workloads + N values are identical to bench.mjs and RuntimeBenchmarks.fs.
import { Effect, Ref, Fiber } from "effect"
import { Bench } from "tinybench"
import {
  runBindAsync,
  runMapAsync,
  runRefAsync,
  runForkAsync,
} from "./port/out/Workloads.js"

const BIND_N = 10000
const MAP_N = 10000
const REF_N = 10000
const FORK_N = 1000

// --- stock Effect programs, built once (identical to bench.mjs) ---

let stockBind = Effect.succeed(0)
for (let i = 0; i < BIND_N; i++) {
  stockBind = Effect.flatMap(stockBind, (x) => Effect.succeed(x + 1))
}

let stockMap = Effect.succeed(0)
for (let i = 0; i < MAP_N; i++) {
  stockMap = Effect.map(stockMap, (x) => x + 1)
}

const stockRef = Effect.gen(function* () {
  const r = yield* Ref.make(0)
  for (let i = 0; i < REF_N; i++) {
    yield* Ref.update(r, (x) => x + 1)
    yield* Ref.get(r)
  }
  return yield* Ref.get(r)
})

const stockFork = Effect.gen(function* () {
  for (let i = 0; i < FORK_N; i++) {
    const fib = yield* Effect.forkChild(Effect.succeed(1))
    yield* Fiber.join(fib)
  }
})

// Both sides run through their Promise runner so the comparison is apples-to-apples.
const stock = {
  bind: () => Effect.runPromise(stockBind),
  map: () => Effect.runPromise(stockMap),
  ref: () => Effect.runPromise(stockRef),
  fork: () => Effect.runPromise(stockFork),
}
const ours = {
  bind: runBindAsync,
  map: runMapAsync,
  ref: runRefAsync,
  fork: runForkAsync,
}

// --- sanity check before timing ---
const sb = await stock.bind(),
  sm = await stock.map(),
  sr = await stock.ref()
const ob = await ours.bind(),
  om = await ours.map(),
  or_ = await ours.ref()
if (sb !== BIND_N || sm !== MAP_N || sr !== REF_N) {
  throw new Error(`stock sanity failed: bind=${sb} map=${sm} ref=${sr}`)
}
if (ob !== BIND_N || om !== MAP_N || or_ !== REF_N) {
  throw new Error(`ours sanity failed: bind=${ob} map=${om} ref=${or_}`)
}
console.log(`sanity ok (both sides): bind=${ob} map=${om} ref=${or_}`)

// --- timing ---
const WORKLOADS = [
  ["bind throughput (10k flatMap)", "bind"],
  ["succeed/map (10k map)", "map"],
  ["Ref update/get (10k)", "ref"],
  ["fork/join (1k)", "fork"],
]

async function timeSide(side) {
  const bench = new Bench({ time: 1500, warmupTime: 300 })
  for (const [name, key] of WORKLOADS) bench.add(name, side[key])
  await bench.run()
  return new Map(bench.tasks.map((t) => [t.name, t.result.latency.mean])) // ms/op
}

const oursMs = await timeSide(ours)
const stockMs = await timeSide(stock)

// --- ratio-ranked report (ours ÷ stock; >1 = we are slower) ---
const fmt = (ms) => (ms >= 1 ? `${ms.toFixed(3)} ms` : `${(ms * 1000).toFixed(1)} µs`)
const verdict = (r) =>
  r <= 1.25 ? "🟢 competitive" : r <= 2 ? "🟡 behind" : "🔴 hotspot"

const rows = WORKLOADS.map(([name]) => {
  const o = oursMs.get(name),
    s = stockMs.get(name)
  return { name, o, s, ratio: o / s }
}).sort((a, b) => b.ratio - a.ratio)

console.log(
  "\nWorkloads sorted worst-ratio-first (eff-sharp ÷ stock). Both: Fable/stock JS on the same Node.\n",
)
console.table(
  rows.map((r) => ({
    Workload: r.name,
    "eff-sharp (JS)": fmt(r.o),
    "stock Effect": fmt(r.s),
    "ratio (ours÷stock)": `${r.ratio.toFixed(2)}×`,
    verdict: verdict(r.ratio),
  })),
)

// --- emit tracked markdown report ---
import { writeFileSync } from "node:fs"
const md = [
  "<!-- generated by js-bench/compare.mjs — do not edit by hand -->",
  "# eff-sharp (Fable JS) vs stock Effect — same-runtime micro-bench",
  "",
  `Both sides are JavaScript on the same Node (${process.version}), driven through their`,
  "async/Promise runner with one tinybench harness — a fair comparison (unlike the old",
  ".NET-vs-JS RESULTS.md). Workloads + N identical to `bench.mjs` / `RuntimeBenchmarks.fs`.",
  "Sorted worst-ratio-first.",
  "",
  "| Workload | eff-sharp (JS) | stock Effect | ratio (ours÷stock) | verdict |",
  "|---|---:|---:|---:|---|",
  ...rows.map(
    (r) => `| ${r.name} | ${fmt(r.o)} | ${fmt(r.s)} | ${r.ratio.toFixed(2)}× | ${verdict(r.ratio)} |`,
  ),
  "",
  "Note: every workload runs via the Promise runner on **both** sides. Under Fable, F#'s",
  "`Async` trampolines deep sync chains, so `runSync` can't drive them on JS; routing stock",
  "through `runPromise` too keeps it apples-to-apples (and is conservative — stock's native",
  "`runSync` would be faster still). The sync-throughput gap is the cost of the `Async`-based",
  "core in generated JS; `fork/join` is competitive because there the async overhead is mutual.",
  "",
].join("\n")
writeFileSync(new URL("./comparison.md", import.meta.url), md)
console.log("\nwrote js-bench/comparison.md")
