#!/usr/bin/env node
// Generates PORTING.md from the filesystem so status can't drift from reality.
// A module is "present" if src/Effect/<Module>.fs exists; "tested" if
// test/<Module>Spec.fs exists. Run: node tools/porting-status.mjs (writes
// PORTING.md); --check exits non-zero if PORTING.md is stale (for CI).
import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const srcDir = join(root, "src/Effect");
const platDir = join(root, "src/Effect.Platform.Node");
const testDir = join(root, "test");

const loc = (p) => readFileSync(p, "utf8").split("\n").length;
const fsFiles = (d) => readdirSync(d).filter((f) => f.endsWith(".fs")).sort();
const specs = new Set(
  readdirSync(testDir)
    .filter((f) => f.endsWith("Spec.fs"))
    .map((f) => f.replace(/Spec\.fs$/, "")),
);

const moduleData = (dir, files) =>
  files
    .filter((f) => !f.endsWith(".fsproj"))
    .map((f) => {
      const mod = f.replace(/\.fs$/, "");
      return { mod, tested: specs.has(mod), loc: loc(join(dir, f)) };
    });

const render = (rows) =>
  rows.map((r) => `| \`${r.mod}\` | ✅ | ${r.tested ? "✅" : "—"} | ${r.loc} |`).join("\n");

const coreData = moduleData(srcDir, fsFiles(srcDir));
const platData = moduleData(platDir, fsFiles(platDir));
const core = render(coreData);
const plat = render(platData);

const coreCount = coreData.length;
const testedCount = coreData.filter((r) => r.tested).length;

const md = `# Porting status

<!-- GENERATED by tools/porting-status.mjs — do not edit by hand.
     Run \`node tools/porting-status.mjs\` to refresh. -->

Inventory of ported modules, generated from the source tree so it can't drift.
A module is **present** when \`src/Effect/<Module>.fs\` exists and **tested** when
\`test/<Module>Spec.fs\` exists. Presence/tests are mechanical facts; semantic
fidelity to effect-smol is assessed separately in
[\`docs/effect4-port-evaluation.md\`](docs/effect4-port-evaluation.md).

**Core modules:** ${coreCount} present · ${testedCount} with specs.
**Platform-node modules:** ${platData.length}.

## Core (\`src/Effect/*.fs\`)

| Module | Present | Spec | LOC |
|--------|:-------:|:----:|----:|
${core}

## Platform / Node (\`src/Effect.Platform.Node/*.fs\`)

| Module | Present | Spec | LOC |
|--------|:-------:|:----:|----:|
${plat}
`;

const out = join(root, "PORTING.md");
if (process.argv.includes("--check")) {
  const current = existsSync(out) ? readFileSync(out, "utf8") : "";
  if (current !== md) {
    console.error("PORTING.md is stale — run `node tools/porting-status.mjs`.");
    process.exit(1);
  }
  console.log("PORTING.md is up to date.");
} else {
  writeFileSync(out, md);
  console.log(`wrote PORTING.md — ${coreCount} core, ${platData.length} platform modules.`);
}
